# see also: https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/configuration.md

update:
  # https://coreos.com/os/docs/latest/update-strategies.html
  group:  "stable"
locksmith:
  reboot_strategy: "reboot"
  window_start:    "Mon 5:00"
  window_length:   "2h"

systemd:
  units:
    # https://coreos.com/os/docs/latest/customizing-sshd.html
    - name: sshd.socket
      dropins:
      - name: 10-sshd-port.conf
        contents: |
          [Socket]
          ListenStream=
          ListenStream=${ssh_port}

storage:
  files:
    # https://coreos.com/os/docs/latest/customizing-sshd.html
    - path: /etc/ssh/sshd_config
      filesystem: root
      mode: 0600
      user:
        name: root
      group:
        name: root
      contents:
        inline: |
          AllowUsers core
          AuthenticationMethods publickey
          ChallengeResponseAuthentication no
          ClientAliveInterval 180
          PasswordAuthentication no
          PermitRootLogin no
          PrintLastLog no # handled by PAM
          PrintMotd no # handled by PAM
          Subsystem sftp internal-sftp
          UsePrivilegeSeparation sandbox
          UseDNS no
          UsePAM yes

    # https://coreos.com/os/docs/latest/customizing-docker.html
    - path: /etc/docker/ca.pem
      filesystem: root
      mode: 0444
      contents:
        local: ca.pem
    - path: /etc/docker/server.pem
      filesystem: root
      mode: 0444
      contents:
        local: server.pem
    - path: /etc/docker/server-key.pem
      filesystem: root
      mode: 0400
      contents:
        local: server-key.pem

systemd:
  units:
    - name: docker-tls-tcp.socket
      enable: true
      contents: |
        [Unit]
        Description=Docker Secured Socket for the API

        [Socket]
        ListenStream=2376
        BindIPv6Only=both
        Service=docker.service

        [Install]
        WantedBy=sockets.target

docker:
  flags:
    - --tlsverify
    - --tlscacert=/etc/docker/ca.pem
    - --tlscert=/etc/docker/server.pem
    - --tlskey=/etc/docker/server-key.pem
